feat: create ImageProvider to load dynamic image resources
ZupIT/beagle-ios pull request #43
Opened 2022-06-04 18:21 UTC by guitar09

### Related Issues

Closes https://github.com/ZupIT/beagle/issues/1816

### Description and Example

To facilitate the process of loading images from multi-module projects in Beagle for iOS, a new protocol to create an ImageProvider, similar how is done in Android, would allow us to load resources from more than one bounded Bundle context.

```swift
public protocol ImageAssetProtocol {
    func loadImageAsset(id: String) -> UIImage?
} 
 ```
### Checklist

Please, check if these important points are met using `[x]`:

- [X] I read the [PR Guide] and followed the process outlined there for submitting this PR.
- [X] I avoided _breaking changes_ by not changing public APIs that people rely on. 
- [X] I am willing to follow-up on review comments in a timely manner.
- [X] I have made the documentation changes or I created an issue explaining how to document this change on [Docs issues](https://github.com/ZupIT/beagle-docs/issues). Please link the issue here:

[PR Guide]: https://github.com/ZupIT/beagle/blob/main/doc/contributing/pull_requests.md

2022-06-21 18:57 UTC, dantes-git requested changes
Thanks for the contribution @guitar09 🎉🚀! You still need to sign the commits you make
with a GPG key and use -s "flag" on commits.

I'll check out the other ci-related issues.

2022-06-21 18:57 UTC, dantes-git commented on Sources/Beagle/Sources/Setup/BeagleConfigurator.swift
> +    public var imageProvider: ImageProviderProtocol = ImageProvider(appBundle: MainBundle())
The ImageProvider should use the bundle configured on dependencies

2022-06-21 18:57 UTC, dantes-git commented on Sources/Beagle/Sources/Bundle/ImageProviderProtocol.swift
> +public struct ImageProvider : ImageProviderProtocol {
The ImageProvider (Default implementation) should be private (or internal) and use bundle setted in dependencies. You can use the mainBundle as inner dependency with `@Injected`.

2022-06-21 21:49 UTC, guitar09 commented on Sources/Beagle/Sources/Setup/BeagleConfigurator.swift
> +    public var imageProvider: ImageProviderProtocol = ImageProvider(appBundle: MainBundle())
Hello @dantes-git , I changed it.

2022-06-21 21:49 UTC, guitar09 commented on Sources/Beagle/Sources/Bundle/ImageProviderProtocol.swift
> +public struct ImageProvider : ImageProviderProtocol {
Hello @dantes-git , I changed it.

2022-06-22 14:24 UTC, dantes-git approved these changes

2022-06-22 14:37 UTC, merged